### ISSUE TITLE
incompatible with Sublime keymap use of ctrl^d multi cursor editing

### ISSUE THREAD

**Issue by odedbd** [jcb91/jupyter_highlight_selected_word#6]
First, let me say thank you for a great extension!

My only problem with using this extension is that it overrides the highlighting of multi-cursor editing using Sublime keymap (ctrl^d) in a way that makes it unusable. The problem is that there is almost no way to see which instances of the selected word are selected in the multi-cursor editing and which are not. 

Perhaps a work around could be to have the "highlight selected word" disabled by default, or at least persistent between notebook loads, so that I could turn the feature on when I need it only.

Thanks again,

**Comment by jcb91** [comment]
> First, let me say thank you for a great extension!

Gald you've found it useful :smile:

> it overrides the highlighting of multi-cursor editing using Sublime keymap (ctrl^d) in a way that makes it unusable

To clarify, do you mean that it's unclear what is being selected because the regular selection highlight is hidden by the selected-word highlight? I've also found this annoying, though I've never used the sublime keymap so haven't come across it in that context.

> Perhaps a work around could be to have the "highlight selected word" disabled by default, or at least persistent between notebook loads, so that I could turn the feature on when I need it only.

Sure, persistence sounds easy to implement, I'll take a crack at it.

**Comment by jcb91** [comment]
Ok, I've tried to address these, and I *think* I may have found a fix, assuming of course that I understood the issue correctly in the first place. I've used the codemirror addon mark-selection to ensure that the highlight is not applied to the currently-selected text, which should hopefully make it obvious which word is the selected one amongst the highlighted ones. I've also made the menu-item status persistent by writing its value to config on change, and added an optional (disabled by default) hotkey binding for toggling it. If you could let me know if this helps/doesn't help/doesn't make sense, that'd be great. If you need further guidance on how to try out the code in the pull request, let me know what OS you're using, and whether you're using conda or pip to perform your installations.

**Comment by odedbd** [comment]
thanks for taking the time to address the issue, much appreciated!

You understood the issue perfectly and the fix you describe sounds great. I would appreciate help in how to test this. My OS is Windows 8 and I am using pip to perform installations.

**Comment by jcb91** [comment]
> thanks for taking the time to address the issue, much appreciated!

No worries, it's one that's been bugging me for a while, so it's nice to have a fix :)

> I would appreciate help in how to test this. My OS is Windows 8 and I am using pip to perform installations.

Ok, so I think you should be able to install the pip package using

    pip install -I https://github.com/jcb91/jupyter_highlight_selected_word/archive/selection_styling.tar.gz

The `-I` flag ensures the existing installation will be ignored, so you'll definitely install the new one even though the version number hasn't changed yet. Then you'll need to install the javascript etc files into the correct place, and enable the nbextension to load in the notebook interface, as in the [installation instructions in the main readme](https://github.com/jcb91/jupyter_highlight_selected_word/blob/ac26a713edc3bcdef2fca2e5e0523642d1e6dc26/README.md#installation) from point 2 onwards. That should be enough to try it out, but if not, you might also need to try clearing your browser cache. Hope that helps!

**Comment by odedbd** [comment]
Thanks, I installed from the URL you provided and followed the installation instructions, but I do not see the change in the behavior of the extension. I also cleared my browser cache and reloaded a couple of times for good measure. I tried this two times, just to make sure.

Is there anywhere I can check a version number in some file to check whether it was updated or not?

**Comment by jcb91** [comment]
Hmm, curious. So you can of course check the content of the various scripts a page loads using the browser's development tools - see [this SO answer on the javascript console](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers) for how to open consoles in most browsers.

Alternatively, you can use the following python snippet to locate & categorise each copy of the `main.js` file:

```python
import os
from jupyter_core.paths import jupyter_path
from jupyter_highlight_selected_word import (
    _jupyter_nbextension_paths, __file__ as ff)

pip_js_path = os.path.join(
    os.path.dirname(ff), _jupyter_nbextension_paths()[0]['src'], 'main.js')
js_paths = [pip_js_path] + [
    os.path.join(p, 'nbextensions', 'highlight_selected_word', 'main.js')
    for p in jupyter_path()]
existing_js = [p for p in js_paths if os.path.exists(p)]

for p in existing_js:
    with open(p, 'r') as f:
        print(('old:   ', 'new:   ')['hotkey' in f.read()], p)
```

It should print an entry for the pip package (first), then one for each installation which exists in any of the jupyter data directories. For me, this gives:

```
old:    /home/josh/miniconda3/envs/jup/lib/python3.5/site-packages/jupyter_highlight_selected_word/static/highlight_selected_word/main.js
new:    /home/josh/miniconda3/envs/jup/share/jupyter/nbextensions/highlight_selected_word/main.js
```

because I've installed the old pip package over the new one, without updating the files installed into the data directory (which as a consequence still has the new version)

**Comment by odedbd** [comment]
This is what I get, all of these say 'old', also I got 3 different installations (totally unintended) which I guess means my installation is totally messed up, right?

('old:   ', 'c:\\users\\odedb\\virtualenv\\myenv\\lib\\site-packages\\jupyter_highlight_selected_word\\static\\highlight_selected_word\\main.js')
('old:   ', 'C:\\Users\\odedb\\AppData\\Roaming\\jupyter\\nbextensions\\highlight_selected_word\\main.js')
('old:   ', 'C:\\ProgramData\\jupyter\\nbextensions\\highlight_selected_word\\main.js')

**Comment by jcb91** [comment]
> This is what I get, all of these say 'old'

Right, from that I deduce that the pip installation didn't go quite to plan. Did you perform it with your virtualenv `myenv` activated? Because that's the one which is being used. Perhaps try uninstalling before installing, to ensure you're getting the new version (though pretty sure the `-I` flag should take care of that!)

> also I got 3 different installations (totally unintended) which I guess means my installation is totally messed up, right?

Not completely, no :wink:. Similarly to the multiple jupyter config directories for a system (see [our readthedocs page](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/config.html) for info), Jupyter allows nbextensions to be installed in three different places:

 * a system-wide jupyter data directory. In some cases (e.g. unix installations, come to mind) there may be more than one system-level data directory.
 * a jupyter data directory specific to the python installation from which the notebook server is running (called sys-prefix after the python `sys.prefix` property)
 * a per-user jupyter data directory

To get a list of the data directories for your system (they vary depending on OS), you can use

    jupyter --paths

and look for the data section.

Which directory nbextensions get installed to is generally controlled using the `--system`, `--sys-prefix` or `--user` flag for the `nbextension install` (or equivalent) command. It seems that you've installed the nbextension into both the system directory (the one beginning `C:\ProgramData\jupyter\nbextensions`), and your per-user directory (the one beginning `C:\Users\odedb\AppData\Roaming`). This isn't exactly a problem, but it may get confusing to have both installations, so it's probably a good idea to remove one of them with

    jupyter nbextension uninstall --system highlight_selected_word

or

    jupyter nbextension uninstall --user highlight_selected_word

Note that this will also disable the nbextension in all config directories (nothign's ever simple, is it?) so you'll need to re-enable it after running either variant. Enabling is handled by the configurator only for per-user config directories, so it probably makes sense to do your re-enabling there too, with

    jupyter nbextension enable --user highlight_selected word

hope all of that makes sense, it's not terribly straightforward, I must admit

**Comment by odedbd** [comment]
Ok, got it. Your snippet for checking where the script is installed was invaluable and I was able to uninstall all irrelevant versions and then install again and get the new version as the active one. The fix is great, exactly what I needed.

Thanks for the fix and for the help in debugging my install!

**Comment by odedbd** [comment]
Actually, I shouldn't close this myself probably, in case you want this as reference for some PR before getting this in the the master branch, right?

**Comment by jcb91** [comment]
> Ok, got it

Great :smile: 

> Actually, I shouldn't close this myself probably, in case you want this as reference for some PR before getting this in the the master branch, right?

It'll get closed once the PR gets merged into master anyway, which I'm about to do, so it's not a big deal either way. But for bigger, more complicated projects, you're right, it would make more sense to leave it open until merge
